### ISSUE TITLE
release with permissive license

### ISSUE THREAD

**Issue by kurtsansom** [tuxication/tecplot-binary-read#1]
Hi, it looks like you haven't touched this code in a while. would you be willing to release under a more permissive license such as BSD or MIT? I would like to use parts of it but the current license makes that difficult.

**Comment by philippemiron** [comment]
Hi, the GPL license was chosen on purpose. You can use and share the modifications.

**Comment by kurtsansom** [comment]
What about the LGPL license? this allows linking with non-GPL code but covers the use and sharing of modifications?
I don't believe GPL allows linking with  more permissivley licensed code?

**Comment by philippemiron** [comment]
I think it's still possible but you are right, it is much simpler with LGPL. I will be changing it.
